[Variables]
BackColor=0,0,0,128
TextColor=255,255,255,255
TextColor2=255,255,255,160
BarColor=255,255,255
BarColorFadeStart=#BarColor#,108
BarColorFadeEnd=#BarColor#,25
BorderColor=192,192,192,64
;Color2=255,255,255,160
;Color3=255,255,255,108
;Color4=255,255,255,25
LightBlue=207,224,255,255
MediumBlue=92,135,209,255
FontName=Trebuchet MS
BarWidth=5

SidebarWidth=200

Drive1=C:
Drive2=E:
Drive3=J:

[StyleText]
StringCase=Upper
;StringEffect=Shadow
FontColor=#TextColor#
FontFace=#FontName#
AntiAlias=1
FontSize=8
ClipString=1

[StyleTitle]
StringAlign=Left
;StringCase=Upper
;StringEffect=Shadow
;StringStyle=Bold
;FontEffectColor=0,0,0,50
FontColor=#ForeColor#
FontFace=#FontName#
FontSize=10
AntiAlias=1
ClipString=1